# Copyright (c) 2024 trag1c

attribute = "#b181ec"

comment = { bg = "#373B4A", fg = "#c4c4c4"  } #"#c4c4c4"

constant = "#b181ec"
"constant.builtin" = { fg = "#fe7ab2" , modifiers = ["italic"] }

"constant.character" = { bg = "#374048", fg = "#C8FFA7"  }  # "#c8ffa7"
"constant.numeric" = "#fdffab"  # { fg = "#fdffab", bg = "#707362" }

constructor = "#ffaff3"

function = "#9ce7ff"

keyword = { fg = "#fe7ab2" , modifiers = ["italic"] }
"keyword.control" = { fg = "#ffd596" , modifiers = ["italic"]  }
"keyword.control.import" = { fg =  "#fe7ab2" , modifiers = ["italic"] }
"keyword.operator" = { fg =  "#ffaff3" , modifiers = ["italic"]  }
"keyword.storage" = { fg =  "#ffd596" , modifiers = ["italic"] }
"keyword.storage.modifier" = { fg =  "#fe7ab2" , modifiers = ["italic"] }


label = "#ffaff3"

operator = "#ffaff3"

punctuation = "#ffaff3"
"punctuation.bracket" = "#ffffff"
"punctuation.delimiter" = "#ffffff"

special = "#b181ec"

string = { bg = "#374048", fg = "#C8FFA7"  } #"#c8ffa7"

tag = { fg = "#fe7ab2" , modifiers = ["italic"] }

type = "#ffaff3"
"type.builtin" = "#ffddfa"

variable = "#ffffff"
"variable.builtin" = {fg = "#fe7ab2" , modifiers = ["italic"] }




# Diff

"diff.plus" = "#4dbf57"
"diff.minus" = "#e21515"
"diff.delta" = "#f3b2ef"




# UI

"ui.background" = { bg = "#292d3e" }

"ui.gutter" = "#747478"
"ui.gutter.selected" = "#ffffff"

"ui.help" = { bg = "#363b52" }
"ui.highlight" = { bg = "#363b52" }

"ui.menu" = { bg = "#393d4e" }
"ui.menu.selected" = { fg = "#000000", bg = "#fffbe8" }

"ui.popup" = { bg = "#363b52" }
"ui.popup.info" = { bg = "#292d3e" }

"ui.selection" = { fg= "#292d3e", bg = "#9CE7FF" }  # { bg = "#4a5270" }
"ui.selection.primary" = { fg= "#292d3e", bg = "#9CE7FF"  }  # fg= "#4E455E",  bg = "#AA82AF"  { bg = "#393f57" }

"ui.statusline" = { fg = "#000000", bg = "#e8fbfff" } # bg = "#fffbe8" }
"ui.statusline.active" = { fg = "#fffbe8", bg = "#303030" }
"ui.statusline.insert" = { bg = "#c8ffa7" }
"ui.statusline.select" = { bg = "#ffd596" }

"ui.text.focus" = { fg = "#fffbe8", modifiers = ["bold"] }
"ui.text.inactive" = "#eeeeee"

"ui.virtual" = "#404661"
"ui.virtual.ruler" = { bg = "#fffbe8" }
"ui.virtual.inlay-hint" = { fg = "#000000", bg = "#fffbe8" }

"diagnostic" = { bg = "#363b52" }
"diagnostic.warning" = { bg = "#613c00" }
"diagnostic.info" = { bg = "#004961" }
"diagnostic.error" = { bg = "#5c0505" }
"diagnostic.hint" = { bg = "#2c0061" }

warning = "#ffd596"
error = "#f44747"
info = "#9ce7ff"
hint = "#d9baff"



# Markup
"markup.heading" = "#ffaff3"
"markup.raw" = {bg = "#363b52"}
"markup.quote" = "#d9baff"

"markup.link.text" = "#c8ffa7"
"markup.link.url" = { fg = "#ffffff", modifiers = ["underlined"] }

"markup.bold" = { fg = "#b181ec", modifiers = ["bold"] }
"markup.italic" = { fg = "#d9baff", modifiers = ["italic"] }
"markup.strikethrough" = { fg = "#ff4a4a", modifiers = ["crossed_out"] }

"markup.list.checked" = "#c8ffa7"
"markup.list.unchecked" = "#ff4a4a"
"markup.list.unnumbered" = "#ffd596"
"markup.list.numbered" = "#ffd596"
